/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriversRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/drivers/': typeof DriversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/drivers': typeof DriversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/drivers/': typeof DriversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drivers' | '/login' | '/drivers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/drivers'
  id: '__root__' | '/' | '/drivers' | '/login' | '/drivers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriversRoute: typeof DriversRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof DriversRoute
    }
  }
}

interface DriversRouteChildren {
  DriversIndexRoute: typeof DriversIndexRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversIndexRoute: DriversIndexRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriversRoute: DriversRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
